..\..\bin\application.exe g_output_g_input_0.data g_output_g_input_0.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_1.data g_output_g_input_1.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_2.data g_output_g_input_2.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_3.data g_output_g_input_3.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_4.data g_output_g_input_4.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_5.data g_output_g_input_5.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_6.data g_output_g_input_6.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_7.data g_output_g_input_7.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_8.data g_output_g_input_8.data g_output.stats config_evaluate.cfg
..\..\bin\application.exe g_output_g_input_9.data g_output_g_input_9.data g_output.stats config_evaluate.cfg
