..\..\bin\application.exe input.data output0.data output.stats config.cfg
..\..\bin\application.exe input.data output1.data output.stats config.cfg
..\..\bin\application.exe input.data output2.data output.stats config.cfg
..\..\bin\application.exe input.data output3.data output.stats config.cfg
..\..\bin\application.exe input.data output4.data output.stats config.cfg
..\..\bin\application.exe input.data output5.data output.stats config.cfg
..\..\bin\application.exe input.data output6.data output.stats config.cfg
..\..\bin\application.exe input.data output7.data output.stats config.cfg
..\..\bin\application.exe input.data output8.data output.stats config.cfg
..\..\bin\application.exe input.data output9.data output.stats config.cfg
